# Generated by Django 5.2.3 on 2025-07-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
