# Generated by Django 5.2.2 on 2025-07-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('journal', '0002_delete_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documentation_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.documentationwidget')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
