# Generated by Django 5.2.3 on 2025-07-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_documentationwidget_documentationitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentationBlock',
        ),
    ]
